Make code xml schema-independent
artipie/nuget-adapter pull request #101
Opened 2020-08-25 16:27 UTC by Sammers21

Closes #100

2020-08-25 16:27 UTC, Sammers21 commented
@olegmoz, please review the PR.

2020-08-26 06:33 UTC, olegmoz requested changes
@Sammers21 thanks, allis good, but could you please add a tests or tests about parsing XML with other schema mentioned in the issue?

2020-08-26 08:05 UTC, Sammers21 commented
@olegmoz, review the PR once again, please.

2020-08-26 08:46 UTC, olegmoz requested changes
@Sammers21 thanks for adding the test, please see the comments

2020-08-26 08:46 UTC, olegmoz commented on src/test/java/com/artipie/nuget/NuspecTest.java
> +                    ("\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?>"
@Sammers21 could you please explain what symbol `\uFEFF` mean? Is it here for a reason?

2020-08-26 08:46 UTC, olegmoz commented on src/test/java/com/artipie/nuget/NuspecTest.java
> +                        + "\n</package>"
@Sammers21 I'd suggesto to build this XML string using `String.join("\n", ...)` method. This will be more in line with our coding style and will allow to remove `StringLiteralsConcatenationCheck`, `OperatorWrapCheck` warnings

2020-08-26 08:46 UTC, olegmoz commented on src/test/java/com/artipie/nuget/NuspecTest.java
> +            ).packageId().toString(),
@Sammers21 method `version` was fixed in this PR as well, I think we should check it in the test as well

2020-08-26 08:56 UTC, Sammers21 commented on src/test/java/com/artipie/nuget/NuspecTest.java
> +                        + "\n</package>"
@olegmoz, don't like this idea.

2020-08-26 08:57 UTC, Sammers21 commented on src/test/java/com/artipie/nuget/NuspecTest.java
> +            ).packageId().toString(),
@olegmoz, done

2020-08-26 08:59 UTC, Sammers21 commented
@olegmoz, review the PR once again, please.

2020-08-26 09:05 UTC, olegmoz requested changes
@Sammers21 two of my comments from previous review haven't been resolved yet

2020-08-26 09:07 UTC, Sammers21 commented
@olegmoz, ну не хочу я убирть плюсики. Так все делают и так удобно. Нет разницы почти никакой и не думаю что это принципиально. А первый тот странный символ отправляет нугет клиент как я и писал

2020-08-26 09:17 UTC, olegmoz commented on src/test/java/com/artipie/nuget/NuspecTest.java
> +                    ("\uFEFF<?xml version=\"1.0\" encoding=\"utf-8\"?>"
@Sammers21 thanks for clarification, it's good to have it here then

2020-08-26 09:21 UTC, olegmoz commented on src/test/java/com/artipie/nuget/NuspecTest.java
> +                        + "\n</package>"
@Sammers21 I don't like this rule about not using `+` with strings either. Though I am not in position to change code style in the project. The checks could be disabled in some special cases, but I do not see anything special here.

2020-08-26 09:25 UTC, olegmoz requested changes
@Sammers21 thanks for update, the issue with code formatting still stands

2020-08-26 09:34 UTC, Sammers21 commented
@olegmoz, review the PR once again, please.

2020-08-26 09:45 UTC, olegmoz approved these changes
@Sammers21 thanks, approved

2020-08-26 09:45 UTC, merged

2020-08-26 09:46 UTC, Sammers21 commented
@olegmoz, release a new version please