#117 - Repository.versions made async
artipie/nuget-adapter pull request #121
Opened 2020-11-12 15:01 UTC by olegmoz

Part of #117 
`Repository.versions` made async
`CompletionStages` extracted for combining multiple stages into single one

2020-11-12 15:36 UTC, olenagerasimova requested changes
@olegmoz one suggestion, please, take a look

2020-11-12 15:36 UTC, olenagerasimova commented on src/main/java/com/artipie/nuget/http/metadata/CompletionStages.java
> +    CompletionStages(final Collection<CompletionStage<T>> stages) {
@olegmoz I'd suggest to add constructor from `Stream<>` to avoid always transforming `stream` to `list`

2020-11-13 07:25 UTC, olegmoz commented on src/main/java/com/artipie/nuget/http/metadata/CompletionStages.java
> +    CompletionStages(final Collection<CompletionStage<T>> stages) {
@olenagerasimova thanks, added new constructor

2020-11-13 07:39 UTC, olenagerasimova approved these changes
@olegmoz thanks, looks good to merge

2020-11-13 07:44 UTC, merged