Create `Nuget` interface
artipie/nuget-adapter pull request #142
Opened 2021-06-10 08:16 UTC by olenagerasimova

Part of #141 
Created interfaces drafts for sdk API.

2021-06-10 08:27 UTC, genryxy requested changes
@olenagerasimova thanks, please see comments

2021-06-10 08:27 UTC, genryxy commented on src/main/java/com/artipie/nuget/Nuget.java
> +public interface Nuget {
@olenagerasimova probably to name like `NugetPackage` or something else because in other repositories we usually use pure name of artifact manager for providing `add`, `remove` and other operations

2021-06-10 08:27 UTC, genryxy commented on src/main/java/com/artipie/nuget/Nuget.java
> +        String normalised();
@olenagerasimova looks like a typo in method name

2021-06-10 09:02 UTC, olenagerasimova commented
@genryxy thanks, I've renamed other interface to name `NugetPackage` this one.

2021-06-10 09:03 UTC, genryxy approved these changes
@olenagerasimova thanks, looks good

2021-06-10 09:07 UTC, olenagerasimova commented
@g4s8 please check/merge

2021-06-10 09:11 UTC, g4s8 requested changes
@olenagerasimova why to duplicate existing interfaces? We already have `Repository` and `Nuspec` with metadata

2021-06-10 09:19 UTC, olenagerasimova commented
@g4s8 skd api we will not work with `Storage` and other abstractions from `asto`, `Repository` interface methods are not suitable at all for the functionality we are going to expose through sdk. `Nuspec` class also have some methods not suitable for sdk, saving metadata to storage for example.

2021-06-10 12:43 UTC, g4s8 commented
> @g4s8 skd api we will not work with `Storage` and other abstractions from `asto`, `Repository` interface methods are not suitable at all for the functionality we are going to expose through sdk. `Nuspec` class also have some methods not suitable for sdk, saving metadata to storage for example.

@olenagerasimova why can't we just ask to use `FileStorage` instead of implementing the full copy of functionality?

2021-06-10 12:55 UTC, olenagerasimova commented
@g4s8 why, for example, should reposervice write input stream with uploading package from `PUT` request to the file system? And I'm not going to re-implement anything, I'll use already existing classes/functionality, I just want to hide these usages of the internal classes in these interfaces implementations.

2021-06-11 07:00 UTC, g4s8 commented
> @g4s8 why, for example, should reposervice write input stream with uploading package from `PUT` request to the file system? And I'm not going to re-implement anything, I'll use already existing classes/functionality, I just want to hide these usages of the internal classes in these interfaces implementations.

@olenagerasimova maybe we can use `Blocking*` prefixes in this case, similar to `artipie/asto` classes? E.g. `BlockingRepository`, etc

2021-06-11 07:17 UTC, olenagerasimova commented
@g4s8 functionality, I'm going to provide as sdk has nothing to do with `Repository`, it will simply parse and extract some information from `.nupkg` provided as `InputStream`. Again, `Repository` interface in completely unsuitable here as is `Blocking` prefix because there is nothing to block, all operations should be performed in standard sequential form.

Nuget adapter already has classes/methods that do what has to be done (unpack and parse `.nupkg`, read metadata), I will use them in the implementations and I want to hide all these usages inside these new implementations as these classes generally are internal classes of the nuget-adapter.

2021-06-11 07:49 UTC, g4s8 commented
> @g4s8 functionality, I'm going to provide as sdk has nothing to do with `Repository`, it will simply parse and extract some information from `.nupkg` provided as `InputStream`. Again, `Repository` interface in completely unsuitable here as is `Blocking` prefix because there is nothing to block, all operations should be performed in standard sequential form.
> 
> Nuget adapter already has classes/methods that do what has to be done (unpack and parse `.nupkg`, read metadata), I will use them in the implementations and I want to hide all these usages inside these new implementations as these classes generally are internal classes of the nuget-adapter.

@olenagerasimova all operations with input/output streams are blocking - since the thread is waiting for read or write method to return. And, I don't think we need to design interfaces only for singe feature requests, it should be suitable for other potential users.

2021-06-11 11:20 UTC, closed without merging