feat: generate index.json
artipie/nuget-adapter pull request #224
Opened 2022-11-03 14:09 UTC by olenagerasimova

part of #221 
Implemented main workflow to add/update index.json. Only one test is added for now, more tests will be added later...

2022-11-07 09:35 UTC, olenagerasimova commented
@dgarus please, reaview

2022-11-08 07:20 UTC, olenagerasimova commented
@dgarus please, review

2022-11-08 07:44 UTC, dgarus requested changes
@olenagerasimova thanks!
Minor comment.

2022-11-08 07:44 UTC, dgarus commented on src/main/java/com/artipie/nuget/IndexJson.java
> +            if (this.input.isPresent()) {
We can make this method shorter by removing `lower` and `upper` variables.

2022-11-08 07:56 UTC, olenagerasimova commented
@dgarus thanks, corrected

2022-11-08 08:23 UTC, dgarus approved these changes
Thanks!
LGTM

2022-11-08 08:26 UTC, merged