feat: test for index.json generation
artipie/nuget-adapter pull request #226
Opened 2022-11-08 08:37 UTC by olenagerasimova

part of #221 
Added more tests for index.json generation and made several fixes (I've missed the highest level json object with `count` and `items` at first). The example of this json can be checked [here]([feat: test for index.json generation](https://github.com/artipie/nuget-adapter/commit/2374d79efb850065991469409265edf9665b5cd6)) in docs.

2022-11-09 10:37 UTC, olenagerasimova commented
@dgarus please, review

2022-11-10 13:14 UTC, dgarus requested changes
@olenagerasimova thanks!
Minor comment.

2022-11-10 13:14 UTC, dgarus commented on src/main/java/com/artipie/nuget/IndexJson.java
>              final JsonArray arr;
Suggest rewrite this method

```
private static List<JsonObject> sortedPackages(final JsonObject newest,
            final String version, final JsonObject old) {
            List<JsonObject> list = Collections.singletonList(newest);
            if (old.containsKey(Update.ITEMS)) {
                final JsonArray items = old.getJsonArray(Update.ITEMS);
                if (!items.isEmpty()) {
                    final JsonObject value = items.get(0).asJsonObject();
                    final JsonArray arr;
                    if (value.containsKey(Update.ITEMS)
                        && !(arr = value.getJsonArray(Update.ITEMS)).isEmpty()) {
                        list = new ArrayList<>(arr.size() + 1);
                        arr.stream().map(JsonValue::asJsonObject)
                            .filter(val -> !version.equals(version(val))).forEach(list::add);
                        list.add(newest);
                        list.sort(Comparator.comparing(val -> new Semver(version(val))));
                    }
                }
            }
            return list;
        }
```

2022-11-10 13:30 UTC, olenagerasimova commented
@dgarus thanks, can we agree on two `if's`? Three conditions seems too much...

2022-11-10 13:45 UTC, dgarus commented
> @dgarus thanks, can we agree on two `if's`? Three conditions seems too much...

ok

2022-11-10 13:47 UTC, merged